### ISSUE TITLE
Declarar la situación del problema

### ISSUE THREAD

**Issue by equipo8cmppi2020** [equipo8cmppi2020/PetEasy#4]
-Daniel Ibarguen
-Juan David Rios

**Comment by marthaduque** [comment]
Tienen que redactarla de acuerdo a la estructura del documento de ppi de la semana 2 de requisitos y debe ser acorde con lo que se aprobo de su proyecto.

**Comment by marthaduque** [comment]
deben eliminar la solución y escribir la consecuencia.
